SET search_path TO nongjing_map, public;

CREATE TABLE IF NOT EXISTS fact_asset_item (
    asset_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_code VARCHAR(32) NOT NULL,
    org_code VARCHAR(32) NOT NULL,
    asset_code VARCHAR(100) NOT NULL UNIQUE,
    asset_name VARCHAR(200) NOT NULL,
    asset_type VARCHAR(100) NOT NULL,
    asset_nature VARCHAR(50) NOT NULL,
    asset_source VARCHAR(100),
    location_desc VARCHAR(300),
    quantity NUMERIC(18,4) NOT NULL DEFAULT 0,
    unit VARCHAR(20),
    original_value NUMERIC(18,2) NOT NULL DEFAULT 0,
    assessed_value NUMERIC(18,2) NOT NULL DEFAULT 0,
    book_value NUMERIC(18,2) NOT NULL DEFAULT 0,
    usable_status VARCHAR(50) NOT NULL,
    acquire_date DATE,
    dispose_date DATE,
    period_month VARCHAR(6) NOT NULL,
    remark VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_fact_asset_item_region_month ON fact_asset_item(region_code, period_month);
CREATE INDEX IF NOT EXISTS idx_fact_asset_item_nature_status ON fact_asset_item(asset_nature, usable_status);

CREATE TABLE IF NOT EXISTS fact_asset_summary_monthly (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_month VARCHAR(6) NOT NULL,
    region_code VARCHAR(32) NOT NULL,
    org_code VARCHAR(32),
    asset_total_value NUMERIC(18,2) NOT NULL DEFAULT 0,
    operating_asset_value NUMERIC(18,2) NOT NULL DEFAULT 0,
    non_operating_asset_value NUMERIC(18,2) NOT NULL DEFAULT 0,
    asset_count INT NOT NULL DEFAULT 0,
    operating_asset_count INT NOT NULL DEFAULT 0,
    non_operating_asset_count INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_fact_asset_summary_monthly UNIQUE (period_month, region_code, org_code)
);
CREATE INDEX IF NOT EXISTS idx_fact_asset_summary_monthly_region_month ON fact_asset_summary_monthly(region_code, period_month);

INSERT INTO fact_asset_item(region_code, org_code, asset_code, asset_name, asset_type, asset_nature, asset_source, location_desc, quantity, unit, original_value, assessed_value, book_value, usable_status, acquire_date, period_month, remark)
VALUES
('460100', 'ORG460100001', 'AST460100001', '村集体物业A座', '经营性固定资产', '经营性', '购置', '海口市龙桥镇主街', 1, '栋', 9800000.00, 10200000.00, 8600000.00, '出租中', DATE '2021-06-15', '202603', '物业租赁类资产'),
('460100', 'ORG460100002', 'AST460100002', '冷链仓储中心', '经营性固定资产', '经营性', '建设', '海口市演丰镇产业园', 1, '座', 8600000.00, 9000000.00, 7200000.00, '运营中', DATE '2022-04-20', '202603', '冷链仓储资产'),
('460400', 'ORG460400001', 'AST460400001', '标准厂房一期', '在建工程', '经营性', '建设', '儋州市木棠产业园', 1, '期', 12800000.00, 13200000.00, 11800000.00, '建设中', DATE '2023-08-01', '202603', '厂房类资产'),
('469028', 'ORG469028001', 'AST469028001', '集体林地资源包', '资源性资产', '非经营性', '划拨', '陵水县椰林片区', 320, '亩', 5200000.00, 4800000.00, 4500000.00, '确权完成', DATE '2020-11-03', '202603', '资源类资产'),
('469027', 'ORG469027001', 'AST469027002', '村级公益服务站', '公益性资产', '非经营性', '财政投入', '乐东县抱由镇中心村', 1, '处', 3600000.00, 3400000.00, 3000000.00, '待整改', DATE '2019-09-10', '202603', '公益类资产')
ON CONFLICT (asset_code) DO NOTHING;

INSERT INTO fact_asset_summary_monthly(period_month, region_code, org_code, asset_total_value, operating_asset_value, non_operating_asset_value, asset_count, operating_asset_count, non_operating_asset_count)
VALUES
('202603', '460100', NULL, 18800000.00, 15800000.00, 3000000.00, 12, 8, 4),
('202603', '460200', NULL, 16500000.00, 11600000.00, 4900000.00, 10, 6, 4),
('202603', '460400', NULL, 24100000.00, 18100000.00, 6000000.00, 14, 9, 5),
('202603', '469027', NULL, 9800000.00, 4200000.00, 5600000.00, 7, 3, 4),
('202603', '469028', NULL, 14300000.00, 6100000.00, 8200000.00, 9, 4, 5),
('202603', '460000', NULL, 83500000.00, 55800000.00, 27700000.00, 52, 30, 22)
ON CONFLICT (period_month, region_code, org_code) DO NOTHING;

INSERT INTO mv_region_topic_rank_monthly(metric_code, topic_code, region_code, region_name, stat_month, rank_no, metric_value)
VALUES
('ASSET.VALUE.TOTAL', 'asset', '460400', '儋州市', '202603', 1, 24100000.00),
('ASSET.VALUE.TOTAL', 'asset', '460100', '海口市', '202603', 2, 18800000.00),
('ASSET.VALUE.TOTAL', 'asset', '460200', '三亚市', '202603', 3, 16500000.00),
('ASSET.VALUE.TOTAL', 'asset', '469028', '陵水县', '202603', 4, 14300000.00),
('ASSET.VALUE.TOTAL', 'asset', '469027', '乐东县', '202603', 5, 9800000.00)
ON CONFLICT DO NOTHING;