SET search_path TO village_finance_ops;

CREATE TABLE IF NOT EXISTS sys_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_code VARCHAR(64) NOT NULL,
    permission_name VARCHAR(128) NOT NULL,
    permission_type VARCHAR(32) NOT NULL,
    parent_id BIGINT,
    path VARCHAR(255),
    component VARCHAR(255),
    icon VARCHAR(64),
    sort_order INT NOT NULL DEFAULT 0,
    enable_flag SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_sys_permission_code ON sys_permission(permission_code);
CREATE INDEX IF NOT EXISTS idx_sys_permission_parent_id ON sys_permission(parent_id);

CREATE TABLE IF NOT EXISTS sys_dict (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dict_type VARCHAR(64) NOT NULL,
    dict_code VARCHAR(64) NOT NULL,
    dict_label VARCHAR(128) NOT NULL,
    dict_value VARCHAR(128) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    enable_flag SMALLINT NOT NULL DEFAULT 1,
    remark VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_sys_dict_type_code ON sys_dict(dict_type, dict_code);

-- =========================
-- Finance baseline missing tables
-- =========================
CREATE TABLE IF NOT EXISTS fin_voucher_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id BIGINT NOT NULL,
    line_no INT NOT NULL,
    subject_id BIGINT NOT NULL,
    summary VARCHAR(255),
    debit_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    credit_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    aux_type VARCHAR(32),
    aux_id BIGINT,
    sort_order INT NOT NULL DEFAULT 0,
    remark VARCHAR(255),
    CONSTRAINT fk_fin_voucher_entry_subject FOREIGN KEY (subject_id) REFERENCES fin_subject(id)
);

CREATE INDEX IF NOT EXISTS idx_fin_voucher_entry_voucher ON fin_voucher_entry(voucher_id);

CREATE TABLE IF NOT EXISTS fin_voucher_attachment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_url VARCHAR(500) NOT NULL,
    file_size BIGINT,
    uploaded_by BIGINT NOT NULL,
    uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fin_voucher_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id BIGINT NOT NULL,
    audit_action VARCHAR(32) NOT NULL,
    auditor_id BIGINT NOT NULL,
    audit_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    remark VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_fin_voucher_audit_log_voucher ON fin_voucher_audit_log(voucher_id);

CREATE TABLE IF NOT EXISTS fin_voucher_recycle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_voucher_id BIGINT NOT NULL,
    voucher_no VARCHAR(64) NOT NULL,
    voucher_date DATE NOT NULL,
    voucher_type VARCHAR(32) NOT NULL,
    book_id BIGINT NOT NULL,
    period_id BIGINT NOT NULL,
    total_debit NUMERIC(18,2) NOT NULL DEFAULT 0,
    total_credit NUMERIC(18,2) NOT NULL DEFAULT 0,
    delete_reason VARCHAR(255),
    deleted_by BIGINT NOT NULL,
    deleted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    restore_flag SMALLINT NOT NULL DEFAULT 0,
    purge_flag SMALLINT NOT NULL DEFAULT 0,
    voucher_snapshot TEXT NOT NULL,
    remark VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_fin_voucher_recycle_original ON fin_voucher_recycle(original_voucher_id);

CREATE TABLE IF NOT EXISTS fin_voucher_recycle_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recycle_id BIGINT NOT NULL,
    line_no INT NOT NULL,
    subject_id BIGINT NOT NULL,
    summary VARCHAR(255),
    debit_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    credit_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    assist_json TEXT,
    remark VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS fin_voucher_operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id BIGINT NOT NULL,
    operation_type VARCHAR(32) NOT NULL,
    operator_id BIGINT NOT NULL,
    operation_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    operation_desc VARCHAR(500),
    before_json TEXT,
    after_json TEXT,
    remark VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_fin_voucher_operation_log_voucher ON fin_voucher_operation_log(voucher_id);

CREATE TABLE IF NOT EXISTS fin_bank_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    account_name VARCHAR(128) NOT NULL,
    bank_name VARCHAR(128),
    account_no VARCHAR(64) NOT NULL,
    init_balance NUMERIC(18,2) NOT NULL DEFAULT 0,
    current_balance NUMERIC(18,2) NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL DEFAULT 'ENABLE',
    subject_id BIGINT,
    remark VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fin_bank_account_book FOREIGN KEY (book_id) REFERENCES fin_book(id),
    CONSTRAINT fk_fin_bank_account_subject FOREIGN KEY (subject_id) REFERENCES fin_subject(id)
);

CREATE INDEX IF NOT EXISTS idx_fin_bank_account_book ON fin_bank_account(book_id);
CREATE INDEX IF NOT EXISTS idx_fin_bank_account_status ON fin_bank_account(status);

CREATE TABLE IF NOT EXISTS fin_cash_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    account_name VARCHAR(128) NOT NULL,
    init_balance NUMERIC(18,2) NOT NULL DEFAULT 0,
    current_balance NUMERIC(18,2) NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL DEFAULT 'ENABLE',
    subject_id BIGINT,
    remark VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fin_cash_account_book FOREIGN KEY (book_id) REFERENCES fin_book(id),
    CONSTRAINT fk_fin_cash_account_subject FOREIGN KEY (subject_id) REFERENCES fin_subject(id)
);

CREATE INDEX IF NOT EXISTS idx_fin_cash_account_book ON fin_cash_account(book_id);
CREATE INDEX IF NOT EXISTS idx_fin_cash_account_status ON fin_cash_account(status);

CREATE TABLE IF NOT EXISTS fin_internal_transfer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    from_account_id BIGINT NOT NULL,
    from_account_type VARCHAR(16) NOT NULL,
    to_account_id BIGINT NOT NULL,
    to_account_type VARCHAR(16) NOT NULL,
    txn_date DATE NOT NULL,
    amount NUMERIC(18,2) NOT NULL,
    voucher_id BIGINT,
    status VARCHAR(16) NOT NULL DEFAULT 'SUCCESS',
    operator_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    remark VARCHAR(255),
    CONSTRAINT fk_fin_internal_transfer_book FOREIGN KEY (book_id) REFERENCES fin_book(id)
);

CREATE INDEX IF NOT EXISTS idx_fin_internal_transfer_book_date ON fin_internal_transfer(book_id, txn_date);

CREATE TABLE IF NOT EXISTS fin_reconciliation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    period_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    account_type VARCHAR(16) NOT NULL,
    account_name VARCHAR(128) NOT NULL,
    book_balance NUMERIC(18,2) NOT NULL DEFAULT 0,
    bank_balance NUMERIC(18,2) NOT NULL DEFAULT 0,
    diff_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    generated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fin_reconciliation_book FOREIGN KEY (book_id) REFERENCES fin_book(id),
    CONSTRAINT fk_fin_reconciliation_period FOREIGN KEY (period_id) REFERENCES fin_period(id)
);

CREATE INDEX IF NOT EXISTS idx_fin_reconciliation_book_period ON fin_reconciliation(book_id, period_id, account_type);

CREATE TABLE IF NOT EXISTS fin_period_close_check (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    close_id BIGINT,
    book_id BIGINT NOT NULL,
    period_id BIGINT NOT NULL,
    check_code VARCHAR(64) NOT NULL,
    check_name VARCHAR(128) NOT NULL,
    check_result VARCHAR(16) NOT NULL,
    error_count INT NOT NULL DEFAULT 0,
    detail_json TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fin_period_close_check_book FOREIGN KEY (book_id) REFERENCES fin_book(id),
    CONSTRAINT fk_fin_period_close_check_period FOREIGN KEY (period_id) REFERENCES fin_period(id)
);

CREATE TABLE IF NOT EXISTS fin_period_reopen_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    period_id BIGINT NOT NULL,
    reopen_no VARCHAR(64) NOT NULL UNIQUE,
    reason VARCHAR(500),
    operator_id BIGINT,
    operate_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    period_status VARCHAR(16) NOT NULL DEFAULT 'OPEN',
    CONSTRAINT fk_fin_period_reopen_book FOREIGN KEY (book_id) REFERENCES fin_book(id),
    CONSTRAINT fk_fin_period_reopen_period FOREIGN KEY (period_id) REFERENCES fin_period(id)
);

CREATE TABLE IF NOT EXISTS fin_period_operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_id BIGINT NOT NULL,
    operation_type VARCHAR(32) NOT NULL,
    operator_id BIGINT,
    operation_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    before_status VARCHAR(32),
    after_status VARCHAR(32),
    operation_desc VARCHAR(500),
    CONSTRAINT fk_fin_period_operation_period FOREIGN KEY (period_id) REFERENCES fin_period(id)
);

CREATE TABLE IF NOT EXISTS fin_subject_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_code VARCHAR(64) NOT NULL,
    category_name VARCHAR(128) NOT NULL,
    balance_direction VARCHAR(8) NOT NULL DEFAULT 'DEBIT',
    enable_flag SMALLINT NOT NULL DEFAULT 1,
    remark VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_subject_category_code ON fin_subject_category(category_code);

CREATE TABLE IF NOT EXISTS fin_subject_balance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    period_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    opening_debit NUMERIC(18,2) NOT NULL DEFAULT 0,
    opening_credit NUMERIC(18,2) NOT NULL DEFAULT 0,
    period_debit NUMERIC(18,2) NOT NULL DEFAULT 0,
    period_credit NUMERIC(18,2) NOT NULL DEFAULT 0,
    closing_debit NUMERIC(18,2) NOT NULL DEFAULT 0,
    closing_credit NUMERIC(18,2) NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fin_subject_balance_book FOREIGN KEY (book_id) REFERENCES fin_book(id),
    CONSTRAINT fk_fin_subject_balance_period FOREIGN KEY (period_id) REFERENCES fin_period(id),
    CONSTRAINT fk_fin_subject_balance_subject FOREIGN KEY (subject_id) REFERENCES fin_subject(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_subject_balance_unique
    ON fin_subject_balance(book_id, period_id, subject_id);

CREATE TABLE IF NOT EXISTS fin_subject_opening (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    opening_year INT NOT NULL,
    opening_period INT NOT NULL DEFAULT 1,
    opening_debit NUMERIC(18,2) NOT NULL DEFAULT 0,
    opening_credit NUMERIC(18,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_fin_subject_opening_book FOREIGN KEY (book_id) REFERENCES fin_book(id),
    CONSTRAINT fk_fin_subject_opening_subject FOREIGN KEY (subject_id) REFERENCES fin_subject(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_subject_opening_unique
    ON fin_subject_opening(book_id, subject_id, opening_year, opening_period);

CREATE TABLE IF NOT EXISTS fin_assist_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assist_code VARCHAR(64) NOT NULL,
    assist_name VARCHAR(128) NOT NULL,
    assist_type VARCHAR(32) NOT NULL DEFAULT 'CUSTOM',
    enable_flag SMALLINT NOT NULL DEFAULT 1,
    remark VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_assist_category_code ON fin_assist_category(assist_code);

CREATE TABLE IF NOT EXISTS fin_assist_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assist_category_id BIGINT NOT NULL,
    item_code VARCHAR(64) NOT NULL,
    item_name VARCHAR(128) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ENABLE',
    remark VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_fin_assist_item_category FOREIGN KEY (assist_category_id) REFERENCES fin_assist_category(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_assist_item_unique
    ON fin_assist_item(assist_category_id, item_code);

CREATE TABLE IF NOT EXISTS fin_subject_assist_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id BIGINT NOT NULL,
    assist_category_id BIGINT NOT NULL,
    required_flag SMALLINT NOT NULL DEFAULT 0,
    enable_flag SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_fin_subject_assist_subject FOREIGN KEY (subject_id) REFERENCES fin_subject(id),
    CONSTRAINT fk_fin_subject_assist_category FOREIGN KEY (assist_category_id) REFERENCES fin_assist_category(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_subject_assist_unique
    ON fin_subject_assist_config(subject_id, assist_category_id);

CREATE TABLE IF NOT EXISTS fin_voucher_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_code VARCHAR(64) NOT NULL,
    template_name VARCHAR(128) NOT NULL,
    book_id BIGINT NOT NULL,
    biz_type VARCHAR(32),
    summary_rule VARCHAR(255),
    status VARCHAR(16) NOT NULL DEFAULT 'ENABLE',
    created_by BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at TIMESTAMP,
    remark VARCHAR(255),
    CONSTRAINT fk_fin_voucher_template_book FOREIGN KEY (book_id) REFERENCES fin_book(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_voucher_template_code
    ON fin_voucher_template(book_id, template_code);

CREATE TABLE IF NOT EXISTS fin_voucher_no_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    prefix VARCHAR(32) NOT NULL DEFAULT 'PZ',
    date_pattern VARCHAR(32) NOT NULL DEFAULT 'yyyyMM',
    padding_len INT NOT NULL DEFAULT 4,
    current_no INT NOT NULL DEFAULT 1,
    reset_rule VARCHAR(16) NOT NULL DEFAULT 'MONTH',
    status VARCHAR(16) NOT NULL DEFAULT 'ENABLE',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fin_voucher_no_rule_book FOREIGN KEY (book_id) REFERENCES fin_book(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_voucher_no_rule_book ON fin_voucher_no_rule(book_id);

CREATE TABLE IF NOT EXISTS fin_voucher_print_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    print_title VARCHAR(128) NOT NULL DEFAULT '记账凭证',
    page_size VARCHAR(16) NOT NULL DEFAULT 'A4',
    show_auditor SMALLINT NOT NULL DEFAULT 1,
    show_attachment SMALLINT NOT NULL DEFAULT 1,
    status VARCHAR(16) NOT NULL DEFAULT 'ENABLE',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fin_voucher_print_config_book FOREIGN KEY (book_id) REFERENCES fin_book(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_voucher_print_config_book ON fin_voucher_print_config(book_id);

CREATE TABLE IF NOT EXISTS fin_voucher_assist_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_entry_id BIGINT NOT NULL,
    assist_category_id BIGINT NOT NULL,
    assist_item_id BIGINT NOT NULL,
    assist_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    remark VARCHAR(255),
    CONSTRAINT fk_fin_voucher_assist_entry_line FOREIGN KEY (voucher_entry_id) REFERENCES fin_voucher_entry(id) ON DELETE CASCADE,
    CONSTRAINT fk_fin_voucher_assist_entry_category FOREIGN KEY (assist_category_id) REFERENCES fin_assist_category(id),
    CONSTRAINT fk_fin_voucher_assist_entry_item FOREIGN KEY (assist_item_id) REFERENCES fin_assist_item(id)
);

CREATE INDEX IF NOT EXISTS idx_fin_voucher_assist_entry_line ON fin_voucher_assist_entry(voucher_entry_id);

CREATE TABLE IF NOT EXISTS fin_income_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_code VARCHAR(64) NOT NULL,
    template_name VARCHAR(128) NOT NULL,
    book_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ENABLE',
    created_by BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    remark VARCHAR(255),
    CONSTRAINT fk_fin_income_template_book FOREIGN KEY (book_id) REFERENCES fin_book(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_income_template_code ON fin_income_template(book_id, template_code);

CREATE TABLE IF NOT EXISTS fin_income_template_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT NOT NULL,
    line_no INT NOT NULL,
    subject_id BIGINT NOT NULL,
    summary_rule VARCHAR(255),
    amount NUMERIC(18,2),
    direction VARCHAR(8) NOT NULL DEFAULT 'DEBIT',
    remark VARCHAR(255),
    CONSTRAINT fk_fin_income_template_item_template FOREIGN KEY (template_id) REFERENCES fin_income_template(id) ON DELETE CASCADE,
    CONSTRAINT fk_fin_income_template_item_subject FOREIGN KEY (subject_id) REFERENCES fin_subject(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_income_template_item_line ON fin_income_template_item(template_id, line_no);

CREATE TABLE IF NOT EXISTS fin_expense_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_code VARCHAR(64) NOT NULL,
    template_name VARCHAR(128) NOT NULL,
    book_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ENABLE',
    created_by BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    remark VARCHAR(255),
    CONSTRAINT fk_fin_expense_template_book FOREIGN KEY (book_id) REFERENCES fin_book(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_expense_template_code ON fin_expense_template(book_id, template_code);

CREATE TABLE IF NOT EXISTS fin_expense_template_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT NOT NULL,
    line_no INT NOT NULL,
    subject_id BIGINT NOT NULL,
    summary_rule VARCHAR(255),
    amount NUMERIC(18,2),
    direction VARCHAR(8) NOT NULL DEFAULT 'CREDIT',
    remark VARCHAR(255),
    CONSTRAINT fk_fin_expense_template_item_template FOREIGN KEY (template_id) REFERENCES fin_expense_template(id) ON DELETE CASCADE,
    CONSTRAINT fk_fin_expense_template_item_subject FOREIGN KEY (subject_id) REFERENCES fin_subject(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_expense_template_item_line ON fin_expense_template_item(template_id, line_no);

CREATE TABLE IF NOT EXISTS fin_cashier_init_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_code VARCHAR(64) NOT NULL,
    template_name VARCHAR(128) NOT NULL,
    book_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ENABLE',
    created_by BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    remark VARCHAR(255),
    CONSTRAINT fk_fin_cashier_init_template_book FOREIGN KEY (book_id) REFERENCES fin_book(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_cashier_init_template_code
    ON fin_cashier_init_template(book_id, template_code);

CREATE TABLE IF NOT EXISTS fin_cashier_init_template_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT NOT NULL,
    line_no INT NOT NULL,
    item_name VARCHAR(128) NOT NULL,
    item_value VARCHAR(255),
    remark VARCHAR(255),
    CONSTRAINT fk_fin_cashier_init_template_item_template FOREIGN KEY (template_id) REFERENCES fin_cashier_init_template(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_cashier_init_template_item_line
    ON fin_cashier_init_template_item(template_id, line_no);

CREATE TABLE IF NOT EXISTS fin_cashier_init_template_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT NOT NULL,
    version_no INT NOT NULL DEFAULT 1,
    publish_flag SMALLINT NOT NULL DEFAULT 0,
    created_by BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    remark VARCHAR(255),
    CONSTRAINT fk_fin_cashier_init_template_version_template FOREIGN KEY (template_id) REFERENCES fin_cashier_init_template(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_cashier_init_template_version_unique
    ON fin_cashier_init_template_version(template_id, version_no);

CREATE TABLE IF NOT EXISTS fin_cashier_init_template_auth (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT NOT NULL,
    auth_type VARCHAR(16) NOT NULL,
    auth_value VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fin_cashier_init_template_auth_template FOREIGN KEY (template_id) REFERENCES fin_cashier_init_template(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_cashier_init_template_auth_unique
    ON fin_cashier_init_template_auth(template_id, auth_type, auth_value);

CREATE TABLE IF NOT EXISTS fin_cashier_init_template_stat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT NOT NULL,
    stat_date DATE NOT NULL,
    apply_count INT NOT NULL DEFAULT 0,
    success_count INT NOT NULL DEFAULT 0,
    fail_count INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fin_cashier_init_template_stat_template FOREIGN KEY (template_id) REFERENCES fin_cashier_init_template(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_cashier_init_template_stat_unique
    ON fin_cashier_init_template_stat(template_id, stat_date);

CREATE TABLE IF NOT EXISTS fin_book_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    operation_type VARCHAR(32) NOT NULL,
    operator_id BIGINT,
    operation_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    before_json TEXT,
    after_json TEXT,
    remark VARCHAR(255),
    CONSTRAINT fk_fin_book_log_book FOREIGN KEY (book_id) REFERENCES fin_book(id)
);

CREATE INDEX IF NOT EXISTS idx_fin_book_log_book_time ON fin_book_log(book_id, operation_time DESC);

CREATE TABLE IF NOT EXISTS fin_multicolumn_ledger_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    column_code VARCHAR(64) NOT NULL,
    column_name VARCHAR(128) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    enable_flag SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_fin_multicolumn_ledger_book FOREIGN KEY (book_id) REFERENCES fin_book(id),
    CONSTRAINT fk_fin_multicolumn_ledger_subject FOREIGN KEY (subject_id) REFERENCES fin_subject(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_multicolumn_ledger_unique
    ON fin_multicolumn_ledger_config(book_id, subject_id, column_code);

CREATE TABLE IF NOT EXISTS fin_income_expense_summary_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    period_id BIGINT NOT NULL,
    snapshot_date DATE NOT NULL,
    income_total NUMERIC(18,2) NOT NULL DEFAULT 0,
    expense_total NUMERIC(18,2) NOT NULL DEFAULT 0,
    net_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fin_income_expense_snapshot_book FOREIGN KEY (book_id) REFERENCES fin_book(id),
    CONSTRAINT fk_fin_income_expense_snapshot_period FOREIGN KEY (period_id) REFERENCES fin_period(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_income_expense_snapshot_unique
    ON fin_income_expense_summary_snapshot(book_id, period_id, snapshot_date);

CREATE TABLE IF NOT EXISTS fin_bank_receipt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_account_id BIGINT NOT NULL,
    journal_id BIGINT,
    receipt_no VARCHAR(64) NOT NULL,
    receipt_date DATE NOT NULL,
    file_url VARCHAR(500),
    download_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    downloaded_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    remark VARCHAR(255),
    CONSTRAINT fk_fin_bank_receipt_bank_account FOREIGN KEY (bank_account_id) REFERENCES fin_bank_account(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_bank_receipt_no ON fin_bank_receipt(receipt_no);
CREATE INDEX IF NOT EXISTS idx_fin_bank_receipt_account_date ON fin_bank_receipt(bank_account_id, receipt_date);

CREATE TABLE IF NOT EXISTS fin_profit_transfer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    period_id BIGINT NOT NULL,
    transfer_no VARCHAR(64) NOT NULL,
    transfer_date DATE NOT NULL,
    total_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    voucher_id BIGINT,
    operator_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    remark VARCHAR(255),
    CONSTRAINT fk_fin_profit_transfer_book FOREIGN KEY (book_id) REFERENCES fin_book(id),
    CONSTRAINT fk_fin_profit_transfer_period FOREIGN KEY (period_id) REFERENCES fin_period(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_profit_transfer_no ON fin_profit_transfer(transfer_no);

CREATE TABLE IF NOT EXISTS fin_profit_transfer_detail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_id BIGINT NOT NULL,
    line_no INT NOT NULL,
    from_subject_id BIGINT NOT NULL,
    to_subject_id BIGINT NOT NULL,
    amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    summary VARCHAR(255),
    CONSTRAINT fk_fin_profit_transfer_detail_transfer FOREIGN KEY (transfer_id) REFERENCES fin_profit_transfer(id) ON DELETE CASCADE,
    CONSTRAINT fk_fin_profit_transfer_detail_from_subject FOREIGN KEY (from_subject_id) REFERENCES fin_subject(id),
    CONSTRAINT fk_fin_profit_transfer_detail_to_subject FOREIGN KEY (to_subject_id) REFERENCES fin_subject(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_profit_transfer_detail_line
    ON fin_profit_transfer_detail(transfer_id, line_no);

CREATE TABLE IF NOT EXISTS fin_period_reverse_close (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    period_id BIGINT NOT NULL,
    reverse_no VARCHAR(64) NOT NULL,
    reverse_reason VARCHAR(500),
    approval_status VARCHAR(16) NOT NULL DEFAULT 'APPROVED',
    operator_id BIGINT,
    reverse_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    remark VARCHAR(255),
    CONSTRAINT fk_fin_period_reverse_close_book FOREIGN KEY (book_id) REFERENCES fin_book(id),
    CONSTRAINT fk_fin_period_reverse_close_period FOREIGN KEY (period_id) REFERENCES fin_period(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_period_reverse_close_no ON fin_period_reverse_close(reverse_no);

-- =========================
-- Party baseline tables
-- =========================
CREATE TABLE IF NOT EXISTS party_org (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_code VARCHAR(64) NOT NULL,
    org_name VARCHAR(128) NOT NULL,
    parent_id BIGINT,
    secretary_name VARCHAR(64),
    status VARCHAR(16) NOT NULL DEFAULT 'ENABLE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS party_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_no VARCHAR(64) NOT NULL,
    member_name VARCHAR(64) NOT NULL,
    id_card_no VARCHAR(32),
    gender VARCHAR(8),
    mobile VARCHAR(32),
    join_date DATE,
    org_id BIGINT,
    status VARCHAR(16) NOT NULL DEFAULT 'NORMAL',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS party_member_transfer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    from_org_id BIGINT,
    to_org_id BIGINT,
    transfer_date DATE NOT NULL,
    approval_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    remark VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS party_course (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code VARCHAR(64) NOT NULL,
    course_name VARCHAR(128) NOT NULL,
    course_type VARCHAR(32),
    publish_status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    published_at TIMESTAMP,
    created_by BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_party_course_code ON party_course(course_code);

CREATE TABLE IF NOT EXISTS party_course_chapter (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    chapter_no INT NOT NULL,
    chapter_name VARCHAR(128) NOT NULL,
    content_url VARCHAR(500),
    duration_seconds INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_party_course_chapter_unique
    ON party_course_chapter(course_id, chapter_no);

CREATE TABLE IF NOT EXISTS party_study_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    chapter_id BIGINT,
    progress_rate NUMERIC(5,2) NOT NULL DEFAULT 0,
    studied_seconds INT NOT NULL DEFAULT 0,
    finished_flag SMALLINT NOT NULL DEFAULT 0,
    last_study_time TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS party_exam (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_code VARCHAR(64) NOT NULL,
    exam_name VARCHAR(128) NOT NULL,
    course_id BIGINT,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    total_score NUMERIC(8,2) NOT NULL DEFAULT 100,
    pass_score NUMERIC(8,2) NOT NULL DEFAULT 60,
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_party_exam_code ON party_exam(exam_code);

CREATE TABLE IF NOT EXISTS party_exam_question (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id BIGINT NOT NULL,
    question_no INT NOT NULL,
    question_type VARCHAR(16) NOT NULL DEFAULT 'SINGLE',
    question_content TEXT NOT NULL,
    answer_content TEXT,
    score NUMERIC(8,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_party_exam_question_unique
    ON party_exam_question(exam_id, question_no);

CREATE TABLE IF NOT EXISTS party_exam_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    score NUMERIC(8,2) NOT NULL DEFAULT 0,
    pass_flag SMALLINT NOT NULL DEFAULT 0,
    submit_time TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_party_exam_result_unique ON party_exam_result(exam_id, member_id);
