CREATE SCHEMA IF NOT EXISTS village_finance_ops;
SET search_path TO village_finance_ops, public;

CREATE TABLE IF NOT EXISTS fin_book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_code VARCHAR(64) NOT NULL UNIQUE,
    book_name VARCHAR(128) NOT NULL,
    org_id BIGINT,
    org_code VARCHAR(64),
    fiscal_year INT NOT NULL,
    currency VARCHAR(16) NOT NULL DEFAULT 'CNY',
    start_date DATE NOT NULL,
    end_date DATE,
    status VARCHAR(16) NOT NULL DEFAULT 'ENABLE',
    remark VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_fin_book_org_code ON fin_book(org_code);
CREATE INDEX IF NOT EXISTS idx_fin_book_status ON fin_book(status);

CREATE TABLE IF NOT EXISTS fin_period (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    period_year INT NOT NULL,
    period_no INT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    close_status VARCHAR(16) NOT NULL DEFAULT 'OPEN',
    close_time TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fin_period_book FOREIGN KEY (book_id) REFERENCES fin_book(id),
    CONSTRAINT uq_fin_period_book UNIQUE (book_id, period_year, period_no)
);

CREATE INDEX IF NOT EXISTS idx_fin_period_book_year ON fin_period(book_id, period_year);

CREATE TABLE IF NOT EXISTS fin_subject (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    subject_code VARCHAR(64) NOT NULL,
    subject_name VARCHAR(128) NOT NULL,
    parent_id BIGINT,
    parent_code VARCHAR(64),
    category_id BIGINT,
    balance_direction VARCHAR(8) NOT NULL,
    level INT NOT NULL,
    is_leaf SMALLINT NOT NULL DEFAULT 1,
    enable_flag SMALLINT NOT NULL DEFAULT 1,
    assist_flag SMALLINT NOT NULL DEFAULT 0,
    remark VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fin_subject_book FOREIGN KEY (book_id) REFERENCES fin_book(id),
    CONSTRAINT uq_fin_subject_code UNIQUE (book_id, subject_code)
);

CREATE INDEX IF NOT EXISTS idx_fin_subject_parent_code ON fin_subject(book_id, parent_code);
CREATE INDEX IF NOT EXISTS idx_fin_subject_enable_flag ON fin_subject(book_id, enable_flag);
