SET search_path TO village_finance_ops, public;

CREATE TABLE IF NOT EXISTS fin_voucher (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_no VARCHAR(64) NOT NULL UNIQUE,
    voucher_date DATE NOT NULL,
    voucher_type VARCHAR(32) NOT NULL,
    book_id BIGINT NOT NULL,
    period_id BIGINT NOT NULL,
    attachment_count INT NOT NULL DEFAULT 0,
    total_debit NUMERIC(18,2) NOT NULL DEFAULT 0,
    total_credit NUMERIC(18,2) NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    audited_by BIGINT,
    audited_at TIMESTAMP,
    remark VARCHAR(255),
    CONSTRAINT fk_fin_voucher_book FOREIGN KEY (book_id) REFERENCES fin_book(id),
    CONSTRAINT fk_fin_voucher_period FOREIGN KEY (period_id) REFERENCES fin_period(id)
);

CREATE INDEX IF NOT EXISTS idx_fin_voucher_book_period ON fin_voucher(book_id, period_id);
CREATE INDEX IF NOT EXISTS idx_fin_voucher_status ON fin_voucher(status);

CREATE TABLE IF NOT EXISTS fin_voucher_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id BIGINT NOT NULL,
    line_no INT NOT NULL,
    subject_id BIGINT NOT NULL,
    summary VARCHAR(255),
    debit_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    credit_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    aux_type VARCHAR(32),
    aux_id BIGINT,
    sort_order INT NOT NULL DEFAULT 0,
    remark VARCHAR(255),
    CONSTRAINT fk_fin_voucher_entry_voucher FOREIGN KEY (voucher_id) REFERENCES fin_voucher(id) ON DELETE CASCADE,
    CONSTRAINT fk_fin_voucher_entry_subject FOREIGN KEY (subject_id) REFERENCES fin_subject(id)
);

CREATE INDEX IF NOT EXISTS idx_fin_voucher_entry_voucher ON fin_voucher_entry(voucher_id);

CREATE TABLE IF NOT EXISTS fin_voucher_attachment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_url VARCHAR(500) NOT NULL,
    file_size BIGINT,
    uploaded_by BIGINT NOT NULL,
    uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fin_voucher_attachment_voucher FOREIGN KEY (voucher_id) REFERENCES fin_voucher(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS fin_voucher_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id BIGINT NOT NULL,
    audit_action VARCHAR(32) NOT NULL,
    auditor_id BIGINT NOT NULL,
    audit_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    remark VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_fin_voucher_audit_log_voucher ON fin_voucher_audit_log(voucher_id);

CREATE TABLE IF NOT EXISTS fin_voucher_recycle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_voucher_id BIGINT NOT NULL,
    voucher_no VARCHAR(64) NOT NULL,
    voucher_date DATE NOT NULL,
    voucher_type VARCHAR(32) NOT NULL,
    book_id BIGINT NOT NULL,
    period_id BIGINT NOT NULL,
    total_debit NUMERIC(18,2) NOT NULL DEFAULT 0,
    total_credit NUMERIC(18,2) NOT NULL DEFAULT 0,
    delete_reason VARCHAR(255),
    deleted_by BIGINT NOT NULL,
    deleted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    restore_flag SMALLINT NOT NULL DEFAULT 0,
    purge_flag SMALLINT NOT NULL DEFAULT 0,
    voucher_snapshot TEXT NOT NULL,
    remark VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_fin_voucher_recycle_original ON fin_voucher_recycle(original_voucher_id);

CREATE TABLE IF NOT EXISTS fin_voucher_recycle_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recycle_id BIGINT NOT NULL,
    line_no INT NOT NULL,
    subject_id BIGINT NOT NULL,
    summary VARCHAR(255),
    debit_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    credit_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    assist_json TEXT,
    remark VARCHAR(255),
    CONSTRAINT fk_fin_voucher_recycle_entry_recycle FOREIGN KEY (recycle_id) REFERENCES fin_voucher_recycle(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS fin_voucher_operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voucher_id BIGINT NOT NULL,
    operation_type VARCHAR(32) NOT NULL,
    operator_id BIGINT NOT NULL,
    operation_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    operation_desc VARCHAR(500),
    before_json TEXT,
    after_json TEXT,
    remark VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_fin_voucher_operation_log_voucher ON fin_voucher_operation_log(voucher_id);
