SET search_path TO village_finance_ops, public;

CREATE TABLE IF NOT EXISTS fin_bank_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    account_name VARCHAR(128) NOT NULL,
    bank_name VARCHAR(128) NOT NULL,
    account_no VARCHAR(64) NOT NULL,
    init_balance NUMERIC(18,2) NOT NULL DEFAULT 0,
    current_balance NUMERIC(18,2) NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL DEFAULT 'ENABLE',
    remark VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fin_bank_account_book FOREIGN KEY (book_id) REFERENCES fin_book(id)
);

CREATE INDEX IF NOT EXISTS idx_fin_bank_account_book ON fin_bank_account(book_id);
CREATE INDEX IF NOT EXISTS idx_fin_bank_account_status ON fin_bank_account(status);

CREATE TABLE IF NOT EXISTS fin_cash_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    account_name VARCHAR(128) NOT NULL,
    init_balance NUMERIC(18,2) NOT NULL DEFAULT 0,
    current_balance NUMERIC(18,2) NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL DEFAULT 'ENABLE',
    remark VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fin_cash_account_book FOREIGN KEY (book_id) REFERENCES fin_book(id)
);

CREATE INDEX IF NOT EXISTS idx_fin_cash_account_book ON fin_cash_account(book_id);
CREATE INDEX IF NOT EXISTS idx_fin_cash_account_status ON fin_cash_account(status);

CREATE TABLE IF NOT EXISTS fin_bank_journal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    txn_date DATE NOT NULL,
    summary VARCHAR(255),
    direction VARCHAR(16) NOT NULL,
    amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    income_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    expense_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    balance NUMERIC(18,2) NOT NULL DEFAULT 0,
    biz_type VARCHAR(32),
    biz_id BIGINT,
    status VARCHAR(16) NOT NULL DEFAULT 'RECORDED',
    created_by BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fin_bank_journal_account FOREIGN KEY (account_id) REFERENCES fin_bank_account(id)
);

CREATE INDEX IF NOT EXISTS idx_fin_bank_journal_account_date ON fin_bank_journal(account_id, txn_date);

CREATE TABLE IF NOT EXISTS fin_cash_journal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    txn_date DATE NOT NULL,
    summary VARCHAR(255),
    direction VARCHAR(16) NOT NULL,
    amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    income_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    expense_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    balance NUMERIC(18,2) NOT NULL DEFAULT 0,
    biz_type VARCHAR(32),
    biz_id BIGINT,
    status VARCHAR(16) NOT NULL DEFAULT 'RECORDED',
    created_by BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fin_cash_journal_account FOREIGN KEY (account_id) REFERENCES fin_cash_account(id)
);

CREATE INDEX IF NOT EXISTS idx_fin_cash_journal_account_date ON fin_cash_journal(account_id, txn_date);

CREATE TABLE IF NOT EXISTS fin_internal_transfer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    from_account_id BIGINT NOT NULL,
    from_account_type VARCHAR(16) NOT NULL,
    to_account_id BIGINT NOT NULL,
    to_account_type VARCHAR(16) NOT NULL,
    txn_date DATE NOT NULL,
    amount NUMERIC(18,2) NOT NULL,
    voucher_id BIGINT,
    status VARCHAR(16) NOT NULL DEFAULT 'SUCCESS',
    operator_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    remark VARCHAR(255),
    CONSTRAINT fk_fin_internal_transfer_book FOREIGN KEY (book_id) REFERENCES fin_book(id)
);

CREATE INDEX IF NOT EXISTS idx_fin_internal_transfer_book_date ON fin_internal_transfer(book_id, txn_date);

CREATE TABLE IF NOT EXISTS fin_reconciliation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    period_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    account_type VARCHAR(16) NOT NULL,
    account_name VARCHAR(128) NOT NULL,
    book_balance NUMERIC(18,2) NOT NULL DEFAULT 0,
    bank_balance NUMERIC(18,2) NOT NULL DEFAULT 0,
    diff_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    generated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fin_reconciliation_book FOREIGN KEY (book_id) REFERENCES fin_book(id),
    CONSTRAINT fk_fin_reconciliation_period FOREIGN KEY (period_id) REFERENCES fin_period(id)
);

CREATE INDEX IF NOT EXISTS idx_fin_reconciliation_book_period ON fin_reconciliation(book_id, period_id, account_type);

CREATE TABLE IF NOT EXISTS fin_period_close (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    period_id BIGINT NOT NULL,
    close_no VARCHAR(64) NOT NULL UNIQUE,
    close_type VARCHAR(16) NOT NULL DEFAULT 'MONTH',
    close_status VARCHAR(16) NOT NULL DEFAULT 'SUCCESS',
    close_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pending_voucher_count INT NOT NULL DEFAULT 0,
    operator_id BIGINT,
    remark VARCHAR(255),
    CONSTRAINT fk_fin_period_close_book FOREIGN KEY (book_id) REFERENCES fin_book(id),
    CONSTRAINT fk_fin_period_close_period FOREIGN KEY (period_id) REFERENCES fin_period(id)
);

CREATE TABLE IF NOT EXISTS fin_period_close_check (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    close_id BIGINT,
    book_id BIGINT NOT NULL,
    period_id BIGINT NOT NULL,
    check_code VARCHAR(64) NOT NULL,
    check_name VARCHAR(128) NOT NULL,
    check_result VARCHAR(16) NOT NULL,
    error_count INT NOT NULL DEFAULT 0,
    detail_json TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fin_period_close_check_close FOREIGN KEY (close_id) REFERENCES fin_period_close(id),
    CONSTRAINT fk_fin_period_close_check_book FOREIGN KEY (book_id) REFERENCES fin_book(id),
    CONSTRAINT fk_fin_period_close_check_period FOREIGN KEY (period_id) REFERENCES fin_period(id)
);

CREATE TABLE IF NOT EXISTS fin_period_reopen_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    period_id BIGINT NOT NULL,
    reopen_no VARCHAR(64) NOT NULL UNIQUE,
    reason VARCHAR(500),
    operator_id BIGINT,
    operate_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    period_status VARCHAR(16) NOT NULL DEFAULT 'OPEN',
    CONSTRAINT fk_fin_period_reopen_book FOREIGN KEY (book_id) REFERENCES fin_book(id),
    CONSTRAINT fk_fin_period_reopen_period FOREIGN KEY (period_id) REFERENCES fin_period(id)
);

CREATE TABLE IF NOT EXISTS fin_period_operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_id BIGINT NOT NULL,
    operation_type VARCHAR(32) NOT NULL,
    operator_id BIGINT,
    operation_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    before_status VARCHAR(32),
    after_status VARCHAR(32),
    operation_desc VARCHAR(500),
    CONSTRAINT fk_fin_period_operation_period FOREIGN KEY (period_id) REFERENCES fin_period(id)
);
