SET search_path TO village_finance_ops, public;

CREATE TABLE IF NOT EXISTS fin_asset_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_code VARCHAR(64) NOT NULL,
    category_name VARCHAR(128) NOT NULL,
    parent_id BIGINT,
    depreciation_years INT,
    depreciation_method VARCHAR(32),
    residual_rate NUMERIC(5,2),
    enable_flag SMALLINT NOT NULL DEFAULT 1,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at TIMESTAMP,
    remark VARCHAR(255)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_asset_category_code ON fin_asset_category(category_code);
CREATE INDEX IF NOT EXISTS idx_fin_asset_category_parent ON fin_asset_category(parent_id);

CREATE TABLE IF NOT EXISTS fin_asset_card (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_code VARCHAR(64) NOT NULL,
    asset_name VARCHAR(128) NOT NULL,
    category_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    org_id BIGINT NOT NULL,
    purchase_date DATE,
    original_value NUMERIC(18,2) NOT NULL DEFAULT 0,
    net_value NUMERIC(18,2) NOT NULL DEFAULT 0,
    accumulated_depreciation NUMERIC(18,2) NOT NULL DEFAULT 0,
    depreciation_method VARCHAR(32),
    depreciation_years INT,
    residual_rate NUMERIC(5,2),
    location VARCHAR(128),
    keeper_name VARCHAR(64),
    status VARCHAR(16) NOT NULL DEFAULT 'USING',
    enable_flag SMALLINT NOT NULL DEFAULT 1,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at TIMESTAMP,
    remark VARCHAR(255),
    CONSTRAINT fk_fin_asset_card_category FOREIGN KEY (category_id) REFERENCES fin_asset_category(id),
    CONSTRAINT fk_fin_asset_card_book FOREIGN KEY (book_id) REFERENCES fin_book(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_asset_card_code ON fin_asset_card(asset_code);
CREATE INDEX IF NOT EXISTS idx_fin_asset_card_category ON fin_asset_card(category_id);
CREATE INDEX IF NOT EXISTS idx_fin_asset_card_book ON fin_asset_card(book_id);
CREATE INDEX IF NOT EXISTS idx_fin_asset_card_status ON fin_asset_card(status);

CREATE TABLE IF NOT EXISTS fin_asset_depreciation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    period_label VARCHAR(32) NOT NULL,
    depreciation_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    accumulated_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    net_value_after NUMERIC(18,2) NOT NULL DEFAULT 0,
    voucher_id BIGINT,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    remark VARCHAR(255),
    CONSTRAINT fk_fin_asset_depreciation_asset FOREIGN KEY (asset_id) REFERENCES fin_asset_card(id),
    CONSTRAINT fk_fin_asset_depreciation_book FOREIGN KEY (book_id) REFERENCES fin_book(id)
);

CREATE INDEX IF NOT EXISTS idx_fin_asset_depreciation_asset ON fin_asset_depreciation(asset_id);

CREATE TABLE IF NOT EXISTS fin_asset_disposal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL,
    disposal_type VARCHAR(32) NOT NULL,
    disposal_date DATE NOT NULL,
    disposal_income NUMERIC(18,2) NOT NULL DEFAULT 0,
    disposal_loss NUMERIC(18,2) NOT NULL DEFAULT 0,
    net_value NUMERIC(18,2),
    voucher_id BIGINT,
    status VARCHAR(16) NOT NULL DEFAULT 'NORMAL',
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    remark VARCHAR(255),
    CONSTRAINT fk_fin_asset_disposal_asset FOREIGN KEY (asset_id) REFERENCES fin_asset_card(id)
);

CREATE INDEX IF NOT EXISTS idx_fin_asset_disposal_asset ON fin_asset_disposal(asset_id);

CREATE TABLE IF NOT EXISTS fin_asset_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_no VARCHAR(64) NOT NULL,
    book_id BIGINT NOT NULL,
    org_id BIGINT NOT NULL,
    inventory_date DATE NOT NULL,
    total_asset_count INT NOT NULL DEFAULT 0,
    actual_asset_count INT NOT NULL DEFAULT 0,
    diff_count INT NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    remark VARCHAR(255),
    CONSTRAINT fk_fin_asset_inventory_book FOREIGN KEY (book_id) REFERENCES fin_book(id)
);

CREATE TABLE IF NOT EXISTS fin_asset_inventory_detail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id BIGINT NOT NULL,
    asset_id BIGINT NOT NULL,
    book_value NUMERIC(18,2) NOT NULL DEFAULT 0,
    actual_value NUMERIC(18,2) NOT NULL DEFAULT 0,
    diff_value NUMERIC(18,2) NOT NULL DEFAULT 0,
    result_type VARCHAR(16) NOT NULL DEFAULT 'NORMAL',
    remark VARCHAR(255),
    CONSTRAINT fk_fin_asset_inventory_detail_inventory FOREIGN KEY (inventory_id) REFERENCES fin_asset_inventory(id),
    CONSTRAINT fk_fin_asset_inventory_detail_asset FOREIGN KEY (asset_id) REFERENCES fin_asset_card(id)
);

CREATE INDEX IF NOT EXISTS idx_fin_asset_inventory_detail_asset ON fin_asset_inventory_detail(asset_id);
