SET search_path TO village_finance_ops, public;

CREATE TABLE IF NOT EXISTS fin_contract_main (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_no VARCHAR(64) NOT NULL,
    contract_name VARCHAR(128) NOT NULL,
    contract_type VARCHAR(64) NOT NULL,
    contract_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    sign_date DATE NOT NULL,
    start_date DATE,
    end_date DATE,
    counterparty_unit VARCHAR(128),
    counterparty_person VARCHAR(64),
    org_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'NORMAL',
    enable_flag SMALLINT NOT NULL DEFAULT 1,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at TIMESTAMP,
    remark VARCHAR(255),
    CONSTRAINT fk_fin_contract_main_book FOREIGN KEY (book_id) REFERENCES fin_book(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_contract_main_no ON fin_contract_main(contract_no);
CREATE INDEX IF NOT EXISTS idx_fin_contract_main_book ON fin_contract_main(book_id);
CREATE INDEX IF NOT EXISTS idx_fin_contract_main_status ON fin_contract_main(status);

CREATE TABLE IF NOT EXISTS fin_contract_change (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL,
    change_type VARCHAR(32) NOT NULL,
    change_date DATE NOT NULL,
    before_amount NUMERIC(18,2),
    after_amount NUMERIC(18,2),
    before_end_date DATE,
    after_end_date DATE,
    change_content VARCHAR(1000),
    voucher_id BIGINT,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    remark VARCHAR(255),
    CONSTRAINT fk_fin_contract_change_main FOREIGN KEY (contract_id) REFERENCES fin_contract_main(id)
);

CREATE INDEX IF NOT EXISTS idx_fin_contract_change_contract ON fin_contract_change(contract_id);

CREATE TABLE IF NOT EXISTS fin_contract_acceptance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL,
    acceptance_date DATE NOT NULL,
    acceptance_result VARCHAR(32) NOT NULL DEFAULT 'PASS',
    acceptance_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    acceptance_desc VARCHAR(1000),
    operator_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    remark VARCHAR(255),
    CONSTRAINT fk_fin_contract_acceptance_main FOREIGN KEY (contract_id) REFERENCES fin_contract_main(id)
);

CREATE INDEX IF NOT EXISTS idx_fin_contract_acceptance_contract ON fin_contract_acceptance(contract_id);

CREATE TABLE IF NOT EXISTS fin_contract_termination (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL,
    termination_date DATE NOT NULL,
    termination_type VARCHAR(32) NOT NULL,
    termination_reason VARCHAR(1000),
    settlement_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    voucher_id BIGINT,
    operator_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    remark VARCHAR(255),
    CONSTRAINT fk_fin_contract_termination_main FOREIGN KEY (contract_id) REFERENCES fin_contract_main(id)
);

CREATE INDEX IF NOT EXISTS idx_fin_contract_termination_contract ON fin_contract_termination(contract_id);

CREATE TABLE IF NOT EXISTS fin_contract_renewal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL,
    renewal_no VARCHAR(64) NOT NULL,
    renewal_date DATE NOT NULL,
    renewal_start_date DATE,
    renewal_end_date DATE,
    renewal_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    renewal_content VARCHAR(1000),
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    remark VARCHAR(255),
    CONSTRAINT fk_fin_contract_renewal_main FOREIGN KEY (contract_id) REFERENCES fin_contract_main(id)
);

CREATE INDEX IF NOT EXISTS idx_fin_contract_renewal_contract ON fin_contract_renewal(contract_id);
CREATE INDEX IF NOT EXISTS idx_fin_contract_renewal_no ON fin_contract_renewal(renewal_no);

CREATE TABLE IF NOT EXISTS fin_contract_attachment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL,
    biz_type VARCHAR(32) NOT NULL DEFAULT 'MAIN',
    file_name VARCHAR(255) NOT NULL,
    file_url VARCHAR(500) NOT NULL,
    file_type VARCHAR(64),
    file_size BIGINT,
    uploaded_by BIGINT NOT NULL,
    uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    remark VARCHAR(255),
    CONSTRAINT fk_fin_contract_attachment_main FOREIGN KEY (contract_id) REFERENCES fin_contract_main(id)
);

CREATE INDEX IF NOT EXISTS idx_fin_contract_attachment_contract ON fin_contract_attachment(contract_id);

CREATE TABLE IF NOT EXISTS fin_contract_operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL,
    operation_type VARCHAR(32) NOT NULL,
    operation_desc VARCHAR(500),
    operator_id BIGINT NOT NULL,
    operation_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    before_json TEXT,
    after_json TEXT,
    remark VARCHAR(255),
    CONSTRAINT fk_fin_contract_log_main FOREIGN KEY (contract_id) REFERENCES fin_contract_main(id)
);

CREATE INDEX IF NOT EXISTS idx_fin_contract_log_contract_time ON fin_contract_operation_log(contract_id, operation_time DESC);
