SET search_path TO village_finance_ops, public;

CREATE TABLE IF NOT EXISTS fin_contract_payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL,
    payment_type VARCHAR(16) NOT NULL,
    payment_date DATE NOT NULL,
    amount NUMERIC(18,2) NOT NULL DEFAULT 0,
    bank_account_id BIGINT,
    cash_account_id BIGINT,
    journal_id BIGINT,
    voucher_id BIGINT,
    status VARCHAR(16) NOT NULL DEFAULT 'NORMAL',
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    remark VARCHAR(255),
    CONSTRAINT fk_fin_contract_payment_main FOREIGN KEY (contract_id) REFERENCES fin_contract_main(id),
    CONSTRAINT fk_fin_contract_payment_bank_account FOREIGN KEY (bank_account_id) REFERENCES fin_bank_account(id),
    CONSTRAINT fk_fin_contract_payment_cash_account FOREIGN KEY (cash_account_id) REFERENCES fin_cash_account(id)
);

CREATE INDEX IF NOT EXISTS idx_fin_contract_payment_contract ON fin_contract_payment(contract_id);
CREATE INDEX IF NOT EXISTS idx_fin_contract_payment_type_date ON fin_contract_payment(payment_type, payment_date);
CREATE INDEX IF NOT EXISTS idx_fin_contract_payment_voucher ON fin_contract_payment(voucher_id);
CREATE INDEX IF NOT EXISTS idx_fin_contract_payment_journal ON fin_contract_payment(journal_id);
