SET search_path TO village_finance_ops, public;

CREATE TABLE IF NOT EXISTS fin_approve_process (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    process_code VARCHAR(64) NOT NULL,
    process_name VARCHAR(128) NOT NULL,
    biz_type VARCHAR(32) NOT NULL,
    version_no INT NOT NULL DEFAULT 1,
    enable_flag SMALLINT NOT NULL DEFAULT 1,
    remark VARCHAR(255),
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_approve_process_code_ver
    ON fin_approve_process(process_code, version_no);
CREATE INDEX IF NOT EXISTS idx_fin_approve_process_biz_type
    ON fin_approve_process(biz_type);

CREATE TABLE IF NOT EXISTS fin_approve_instance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    process_id BIGINT NOT NULL,
    biz_type VARCHAR(32) NOT NULL,
    biz_id BIGINT NOT NULL,
    instance_no VARCHAR(64) NOT NULL,
    applicant_id BIGINT NOT NULL,
    current_node VARCHAR(64),
    approve_status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    start_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP,
    remark VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_fin_approve_instance_process FOREIGN KEY (process_id) REFERENCES fin_approve_process(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_approve_instance_no
    ON fin_approve_instance(instance_no);
CREATE INDEX IF NOT EXISTS idx_fin_approve_instance_process
    ON fin_approve_instance(process_id);
CREATE INDEX IF NOT EXISTS idx_fin_approve_instance_biz
    ON fin_approve_instance(biz_type, biz_id);
CREATE INDEX IF NOT EXISTS idx_fin_approve_instance_status
    ON fin_approve_instance(approve_status);

CREATE TABLE IF NOT EXISTS fin_approve_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id BIGINT NOT NULL,
    task_no VARCHAR(64) NOT NULL,
    node_name VARCHAR(128) NOT NULL,
    approver_id BIGINT NOT NULL,
    task_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    action_type VARCHAR(32),
    action_time TIMESTAMP,
    action_remark VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_fin_approve_task_instance FOREIGN KEY (instance_id) REFERENCES fin_approve_instance(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_fin_approve_task_no
    ON fin_approve_task(task_no);
CREATE INDEX IF NOT EXISTS idx_fin_approve_task_approver_status
    ON fin_approve_task(approver_id, task_status);
CREATE INDEX IF NOT EXISTS idx_fin_approve_task_instance
    ON fin_approve_task(instance_id);

CREATE TABLE IF NOT EXISTS fin_approve_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id BIGINT NOT NULL,
    node_name VARCHAR(128) NOT NULL,
    approver_id BIGINT NOT NULL,
    action_type VARCHAR(32) NOT NULL,
    action_result VARCHAR(16) NOT NULL,
    action_time TIMESTAMP NOT NULL,
    action_remark VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fin_approve_history_instance FOREIGN KEY (instance_id) REFERENCES fin_approve_instance(id)
);

CREATE INDEX IF NOT EXISTS idx_fin_approve_history_instance_time
    ON fin_approve_history(instance_id, action_time DESC);
